### ISSUE TITLE
Delete all changes made since the initial rewrite.

### ISSUE THREAD

**Issue by Deftu** [W-OVERFLOW/W-CORE#3]
I humbly request that all work I've done on this project be deleted.

**Comment by pauliesnug** [comment]
You added all the code from the Incrie respective projects, licensed under the LGPL-3.0 license. OneCore doesn’t break this license. If you would like, we can credit you for all the code and state any further changes. You can also make a pull request removing the code you feel isn’t under the Incrie project such as the 1.8.9 implementations.

**Comment by Zetvue** [comment]
doodaa

**Comment by Aynobody** [comment]
guys is this the suggestions page for sex mod

**Comment by Scherso** [comment]
not funny zetvue, didn’t laugh
